const TRIGGER_DB_SUFFIX = 'alarmservice';
const DEFAULT_TRIGGER_COUNT = 1000000;
const RETRIES_BEFORE_DELETE = 5;

module.exports = {
    TRIGGER_DB_SUFFIX: TRIGGER_DB_SUFFIX,
    DEFAULT_TRIGGER_COUNT: DEFAULT_TRIGGER_COUNT,
    RETRIES_BEFORE_DELETE: RETRIES_BEFORE_DELETE
};
