const TRIGGER_DB_SUFFIX = 'alarmservice';
const DEFAULT_MAX_TRIGGERS = -1;
const RETRY_ATTEMPTS = 10;
const RETRY_DELAY = 1000; //in milliseconds
const REDIS_KEY = 'active';
const DESIGN_DOC_NAME = 'triggers';
const FILTER_FUNCTION = 'only_triggers_by_worker';


module.exports = {
    TRIGGER_DB_SUFFIX: TRIGGER_DB_SUFFIX,
    DEFAULT_MAX_TRIGGERS: DEFAULT_MAX_TRIGGERS,
    RETRY_ATTEMPTS: RETRY_ATTEMPTS,
    RETRY_DELAY: RETRY_DELAY,
    REDIS_KEY: REDIS_KEY,
    DESIGN_DOC_NAME: DESIGN_DOC_NAME,
    FILTER_FUNCTION: FILTER_FUNCTION
};
